# Site settings
title: Ricardo Loo
description: 'Google Employee - Android Framework'
url: https://www.ricalo.com
baseurl: /
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: Ricardo Loo
  email: me@ricalo.com
  twitter_username: ricalo
  facebook_username: ricalodev
  github_username:  ricalo
  linkedin_username:  ricalo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
